### PR TITLE
fix: pod metrics when pod is terminal

### LINKED ISSUE #2403: Negative values on karpenter_pods_startup_duration_seconds
### Description

**Observed Behavior**:
I am getting negative values on 1.6.0 on metric `karpenter_pods_startup_duration_seconds`. This didn't happen on 1.5.0

```
# HELP karpenter_pods_startup_duration_seconds The time from pod creation until the pod is running.
# TYPE karpenter_pods_startup_duration_seconds summary
karpenter_pods_startup_duration_seconds{quantile="0"} -9.223372036854776e+09
karpenter_pods_startup_duration_seconds{quantile="0.5"} 16
karpenter_pods_startup_duration_seconds{quantile="0.9"} 96
karpenter_pods_startup_duration_seconds{quantile="0.99"} 171
karpenter_pods_startup_duration_seconds{quantile="1"} 186
karpenter_pods_startup_duration_seconds_sum -6.456359356198343e+10
karpenter_pods_startup_duration_seconds_count 339
```

When I calculate average as `sum/count` this huge negative number in `sum` - `-6.456359356198343e+10` makes the result in negative days.
**Expected Behavior**:
I can't see how this could be negative so seems like a bug. The pod age can only start at 0 and grow.
**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.6.0
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jigisha620**
Fixes #2403 

**Description**
`karpenter_pods_startup_duration_seconds` is taking negative values for terminal pods because pod status condition Ready is set to False for terminal pods. 

**How was this change tested?**
Added unit tests. Deployed to my dev cluster.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/metrics/pod/controller.go [hunk 1]
```diff
@@ -319,9 +319,11 @@ func (c *Controller) recordPodStartupMetric(pod *corev1.Pod, schedulableTime tim
 				podName:      pod.Name,
 				podNamespace: pod.Namespace,
 			})
-			PodStartupDurationSeconds.Observe(cond.LastTransitionTime.Sub(pod.CreationTimestamp.Time).Seconds(), nil)
-			if !schedulableTime.IsZero() {
-				PodProvisioningStartupDurationSeconds.Observe(cond.LastTransitionTime.Sub(schedulableTime).Seconds(), nil)
+			if ready {
```
Comment (rschalo) [inline pkg/controllers/metrics/pod/controller.go]: Can we actually just handle this in one `if ready` and then perform the same logic in an `else if` for `podutils.IsTerminal`?

Comment (jmdeal) [reply pkg/controllers/metrics/pod/controller.go]: +1 - I don't mind the minimal duplication in this case since it keeps us explicit about what we're doing for each case. It's also worth leaving a comment regarding why we have to differentiate between ready and terminal pods. I don't think the updated last transition time on the status time is obvious unless you've looked into the issue.

File: pkg/controllers/metrics/pod/suite_test.go [hunk 2]
```diff
@@ -287,9 +289,9 @@ var _ = Describe("Pod Metrics", func() {
 		Expect(found).To(BeFalse())
 
 		_, found = FindMetricWithLabelValues("karpenter_pods_startup_duration_seconds", nil)
-		Expect(found).To(BeTrue())
+		Expect(found).To(BeFalse())
```
Comment (jmdeal) [inline pkg/controllers/metrics/pod/suite_test.go:292]: The name of this test is no longer accurate, is it? We're no longer updating the startup time metrics, just the unstarted time metrics

File: pkg/controllers/metrics/pod/suite_test.go [hunk 3]
```diff
@@ -330,9 +332,9 @@ var _ = Describe("Pod Metrics", func() {
...
```
Comment (jmdeal) [inline pkg/controllers/metrics/pod/suite_test.go:335]: Same comment on this test - we're no longer updating the started time metrics

File: pkg/controllers/metrics/pod/controller.go (hunk 1 above)
Comment (jigisha620) [reply pkg/controllers/metrics/pod/controller.go]: Done

File: pkg/controllers/metrics/pod/suite_test.go (hunk 2 above)
Comment (jigisha620) [reply pkg/controllers/metrics/pod/suite_test.go:292]: Updated

File: pkg/controllers/metrics/pod/suite_test.go (hunk 3 above)
Comment (jigisha620) [reply pkg/controllers/metrics/pod/suite_test.go:335]: Updated

File: pkg/controllers/metrics/pod/controller.go [hunk 4]
```diff
@@ -326,6 +326,22 @@ func (c *Controller) recordPodStartupMetric(pod *corev1.Pod, schedulableTime tim
 			c.pendingPods.Delete(key)
 			// Clear cluster state's representation of these pods as we don't need to keep track of them anymore
 			c.cluster.ClearPodSchedulingMappings(client.ObjectKeyFromObject(pod))
+		} else if podutils.IsTerminal(pod) {
+			// We do not emit the startup duration metric for pods that are terminal because such pods will have
+			// Ready status condition set to False which will cause the metric to take negative values.
```
Comment (jmdeal) [inline pkg/controllers/metrics/pod/controller.go:331]: I'd specifically call out that the last transition time was updated when it transitioned to false after the pod went terminal

Comment (jigisha620) [reply pkg/controllers/metrics/pod/controller.go:331]: But in this case more than that lastTransitionTime, it's the fact that `cond` stores Ready condition if it's set to true. If not then ideally there's no valid lastTransitionTime stored -
```
cond, ready := lo.Find(pod.Status.Conditions, func(c corev1.PodCondition) bool {
return c.Type == corev1.PodReady && c.Status == corev1.ConditionTrue
})
```

Comment (jmdeal) [reply pkg/controllers/metrics/pod/controller.go:331]: Ah got it, I misremembered the exact issue a bit. Sounds good then.
