### PR TITLE
fix: BREAKING put karpenter_ignored_pod_count metric under scheduler subsystem

### LINKED ISSUE #1992: `karpenter_ignored_pod_count` is not put under a subsystem
### Description

**Observed Behavior**:

Karpenter has an alpha metric called `karpenter_ignored_pod_count` which should be put in the `scheduler` namespace but wasn't

**Expected Behavior**:

This metric should be in the `scheduler` namespace and should be named `karpenter_scheduler_ignored_pod_count` to align with other metrics that we have about the count of pods that fail to schedule.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by olegy2008**
Fixes #1992

**Description**
Put `karpenter_ignored_pod_count` metric under `scheduler` subsystem, new metric name is: `karpenter_scheduler_ignored_pod_count`.

**How was this change tested?**
1 . Made temporary changes:
```diff
diff --git a/Makefile b/Makefile
index 3029f80..ffe428d 100644
--- a/Makefile
+++ b/Makefile
@@ -67,13 +67,11 @@ delete: ## Delete the controller from your ~/.kube/config cluster
 	helm uninstall karpenter --namespace $(KARPENTER_NAMESPACE)
 
 test: ## Run tests
-	go test ./pkg/... \
+	go test ./pkg/controllers/provisioning \
 		-race \
 		-timeout 20m \
-		--ginkgo.focus="${FOCUS}" \
 		--ginkgo.randomize-all \
-		--ginkgo.v \
-		-cover -coverprofile=coverage.out -outputdir=. -coverpkg=./...
+		--ginkgo.v
 
 deflake: ## Run randomized, racing tests until the test fails to catch flakes
 	ginkgo \
diff --git a/pkg/controllers/provisioning/suite_test.go b/pkg/controllers/provisioning/suite_test.go
index 1174ef9..46d34a7 100644
--- a/pkg/controllers/provisioning/suite_test.go
+++ b/pkg/controllers/provisioning/suite_test.go
@@ -1631,7 +1631,7 @@ var _ = Describe("Provisioning", func() {
 		BeforeEach(func() {
 			storageClass = test.StorageClass(test.StorageClassOptions{Zones: []string{"test-zone-2", "test-zone-3"}})
 		})
-		It("should not schedule if invalid pvc", func() {
+		FIt("should not schedule if invalid pvc", func() {
 			ExpectApplied(ctx, env.Client, test.NodePool())
 			pod := test.UnschedulablePod(test.PodOptions{
 				PersistentVolumeClaims: []string{"invalid"},
diff --git a/pkg/test/expectations/expectations.go b/pkg/test/expectations/expectations.go
index 060ec78..b459422 100644
--- a/pkg/test/expectations/expectations.go
+++ b/pkg/test/expectations/expectations.go
@@ -567,6 +567,7 @@ func FindMetricWithLabelValues(name string, labelValues map[string]string) (*pro
 func ExpectMetricGaugeValue(collector opmetrics.GaugeMetric, expectedValue float64, labels map[string]string) {
 	GinkgoHelper()
 	metricName := ExpectMetricName(collector.(*opmetrics.PrometheusGauge))
+	fmt.Println("metricName is:", metricName)
 	metric, ok := FindMetricWithLabelValues(metricName, labels)
 	Expect(ok).To(BeTrue(), "Metric "+metricName+" should be available")
 	Expect(lo.FromPtr(metric.Gauge.Value)).To(Equal(expectedValue), "Metric "+metricName+" should have the expected value")

```

2. Executed:
```
make test
```

3. Result (truncated):
```
metricName is: karpenter_scheduler_ignored_pod_count
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/provisioning/scheduling/metrics.go [hunk 1]
```diff
@@ -74,6 +74,7 @@ var (
 		crmetrics.Registry,
 		prometheus.GaugeOpts{
 			Namespace: metrics.Namespace,
+			Subsystem: schedulerSubsystem,
 			Name:      "ignored_pod_count",
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/scheduling/metrics.go:78]:
```suggestion
			Name:      "ignored_pods_count",
```

Given that we use `pods` in other metrics, can we also change this to plural for consistency?

**Review by jonathan-innis — COMMENTED** [review]
Thanks for contributing! Just one comment!

File: pkg/controllers/provisioning/scheduling/metrics.go (hunk 1 above)
Comment (olegy2008) [reply pkg/controllers/provisioning/scheduling/metrics.go]: Absolutely
