### PR TITLE
fix: Ensure all patch calls can conflict when resource version doesn't match

### LINKED ISSUE #1578: Failure to delete NodeClaim (Reconciler error)
### Description

**Observed Behavior**:

When deleting NodePools, one of the NodeClaims got stuck and couldn't be deleted. The Node itself does get deleted, and is no longer shown in `get nodes` output, and the EC2 instance is terminated. 

Controller logs show an error:

> {"level":"ERROR","time":"2024-08-16T19:21:14.386Z","logger":"controller","message":"Reconciler error","commit":"5bdf9c3","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"system-6ss2w"},"namespace":"","name":"system-6ss2w","reconcileID":"ea1cb048-d9a1-41b9-95c6-2c89fca2402e","error":"removing termination finalizer, NodeClaim.karpenter.sh \"system-6ss2w\" is invalid: spec: Invalid value: \"object\": spec is immutable"}

Besides this one particular NodeClaim, other NodeClaims were deleted successfully.

Note: Karpenter is installed with webhook **disabled**.

**Expected Behavior**:

NodeClaim is deleted.

**Reproduction Steps** (Please include YAML):

1. Create the following nodeclass and 2 nodepools:

```yaml
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: myorg-default
spec:
  amiSelectorTerms:
  - alias: bottlerocket@latest
  role: KarpenterNodeRole-${CLUSTER_NAME}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${CLUSTER_NAME}
      kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: ${CLUSTER_NAME}
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: apps
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: myorg-default
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "1024"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: myorg-default
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "1024"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        myorg.com/system: shared
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: myorg-default
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "1024"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "2048"
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "1"
      taints:
      - effect: NoSchedule
        key: myorg.com/system
        value: "true"
```

2. Deploy some apps that use both nodepools (including daemonsets).
3. Delete nodepools and nodeclass.

**Versions**:
- Chart Version: v1.0.0
- Kubernetes Version (`kubectl version`): Server Version: v1.30.3-eks-2f46c53

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jonathan-innis**
Fixes #1578

**Description**

This change ensures that calls to Patch that would fully replace portions of the spec like lists continue to conflict if the resource has changed since the controller first retrieved the resource.

This fixes the issue in #1578 where resource quantities are converted to different strings during deserialization and then re-serialization back by ensuring that the request that we send to the apiserver only represents the parts of the resource that we intend to change.

This allows us to keep the NodeClaim immutability checks that we have.

**How was this change tested?**

`make presubmit`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/disruption/controller.go [hunk 1]
```diff
@@ -201,7 +207,7 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
 	})
 	// Cordon the old nodes before we launch the replacements to prevent new pods from scheduling to the old nodes
 	if err := state.RequireNoScheduleTaint(ctx, c.kubeClient, true, stateNodes...); err != nil {
-		return multierr.Append(fmt.Errorf("tainting nodes (command-id: %s), %w", commandID, err), state.RequireNoScheduleTaint(ctx, c.kubeClient, false, stateNodes...))
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:204]: Why are we removing this ? 

nvm, synced offline. Requiring the taint to not exist on all taints that aren't in the orchestration queue is a pre-condition to the reconcile loop. We only taint one set of nodes per reconcile loop, so we can always rely on the loop short circuiting on failure and untainting at the beginning of the loop.

File: pkg/controllers/disruption/controller.go [hunk 2]
```diff
@@ -132,6 +132,9 @@ func (c *Controller) Reconcile(ctx context.Context) (reconcile.Result, error) {
 	if err := state.RequireNoScheduleTaint(ctx, c.kubeClient, false, lo.Filter(c.cluster.Nodes(), func(s *state.StateNode, _ int) bool {
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:132]: Can you update the comment here to change from "If Karpenter restarts during a disruption action", since now we're relying on this every time we fail an action, even if Karpenter hasn't restarted?

File: pkg/controllers/node/termination/controller.go [hunk 3]
```diff
@@ -100,10 +100,13 @@ func (c *Controller) finalize(ctx context.Context, node *corev1.Node) (reconcile
 		return reconcile.Result{}, err
 	}
 
-	if err := c.terminator.Taint(ctx, node, v1.DisruptedNoScheduleTaint); err != nil {
-		return reconcile.Result{}, fmt.Errorf("tainting node with %s, %w", v1.DisruptedTaintKey, err)
+	if err = c.terminator.Taint(ctx, node, v1.DisruptedNoScheduleTaint); err != nil {
+		if errors.IsConflict(err) {
+			return reconcile.Result{Requeue: true}, nil
+		}
+		return reconcile.Result{}, client.IgnoreNotFound(fmt.Errorf("tainting node with %s, %w", v1.DisruptedTaintKey, err))
```
Comment (njtran) [inline pkg/controllers/node/termination/controller.go:107]: musing: I wonder if this should be the string representation of the taint, not just the key string

File: pkg/controllers/node/termination/terminator/terminator.go [hunk 4]
```diff
@@ -73,7 +73,10 @@ func (t *Terminator) Taint(ctx context.Context, node *corev1.Node, taint corev1.
 		corev1.LabelNodeExcludeBalancers: "karpenter",
 	})
 	if !equality.Semantic.DeepEqual(node, stored) {
-		if err := t.kubeClient.Patch(ctx, node, client.StrategicMergeFrom(stored)); err != nil {
+		// We use client.MergeFromWithOptimisticLock because patching a list with a JSON merge patch
+		// can cause races due to the fact that it fully replaces the list on a change
+		// Here, we are updating the taint list
```
Comment (njtran) [inline pkg/controllers/node/termination/terminator/terminator.go:78]: Also node labels, but that's not important for merge patches, since it's a map.

File: pkg/controllers/node/termination/terminator/terminator.go [hunk 5]
```diff
@@ -73,7 +73,10 @@ func (t *Terminator) Taint(ctx context.Context, node *corev1.Node, taint corev1.
...
+		if err := t.kubeClient.Patch(ctx, node, client.MergeFromWithOptions(stored, client.MergeFromWithOptimisticLock{})); err != nil {
```
Comment (njtran) [inline pkg/controllers/node/termination/terminator/terminator.go:79]: Why not strategic merge?

File: pkg/controllers/nodeclaim/lifecycle/initialization.go [hunk 6]
```diff
@@ -74,7 +74,7 @@ func (i *Initialization) Reconcile(ctx context.Context, nodeClaim *v1.NodeClaim)
 	stored := node.DeepCopy()
 	node.Labels = lo.Assign(node.Labels, map[string]string{v1.NodeInitializedLabelKey: "true"})
 	if !equality.Semantic.DeepEqual(stored, node) {
-		if err = i.kubeClient.Patch(ctx, node, client.StrategicMergeFrom(stored)); err != nil {
+		if err = i.kubeClient.Patch(ctx, node, client.MergeFrom(stored)); err != nil {
```
Comment (njtran) [inline pkg/controllers/nodeclaim/lifecycle/initialization.go:77]: Why change from strategic merge?

File: pkg/controllers/nodeclaim/termination/controller.go [hunk 7]
```diff
@@ -125,12 +124,13 @@ func (c *Controller) finalize(ctx context.Context, nodeClaim *v1.NodeClaim) (rec
 			metrics.NodePoolLabel: nodeClaim.Labels[v1.NodePoolLabelKey],
 		}).Observe(time.Since(nodeClaim.StatusConditions().Get(v1.ConditionTypeInstanceTerminating).LastTransitionTime.Time).Seconds())
 	}
+	stored := nodeClaim.DeepCopy() // The NodeClaim may have been modified in the EnsureTerminated function
 	controllerutil.RemoveFinalizer(nodeClaim, v1.TerminationFinalizer)
 	if !equality.Semantic.DeepEqual(stored, nodeClaim) {
-		// We call Update() here rather than Patch() because patching a list with a JSON merge patch
+		// We use client.MergeFromWithOptimisticLock because patching a list with a JSON merge patch
 		// can cause races due to the fact that it fully replaces the list on a change
-		// https://github.com/kubernetes/kubernetes/issues/111643#issuecomment-2016489732
```
Comment (njtran) [inline pkg/controllers/nodeclaim/termination/controller.go:132]: issue no longer necessary?

File: pkg/controllers/state/statenode.go [hunk 8]
```diff
@@ -507,7 +507,10 @@ func RequireNoScheduleTaint(ctx context.Context, kubeClient client.Client, addTa
 			node.Spec.Taints = append(node.Spec.Taints, v1.DisruptedNoScheduleTaint)
 		}
 		if !equality.Semantic.DeepEqual(stored, node) {
-			if err := kubeClient.Patch(ctx, node, client.StrategicMergeFrom(stored)); err != nil {
+			// We use client.MergeFromWithOptimisticLock because patching a list with a JSON merge patch
+			// can cause races due to the fact that it fully replaces the list on a change
+			// Here, we are updating the taint list
+			if err := kubeClient.Patch(ctx, node, client.MergeFromWithOptions(stored, client.MergeFromWithOptimisticLock{})); err != nil {
```
Comment (njtran) [inline pkg/controllers/state/statenode.go:513]: same here on strategic merge

File: pkg/utils/pretty/pretty.go [hunk 9]
```diff
@@ -77,3 +78,7 @@ func Map[K constraints.Ordered, V any](values map[K]V, maxItems int) string {
 	}
 	return buf.String()
 }
+
+func Taint(t v1.Taint) string {
+	return fmt.Sprintf("%s=%s:%s", t.Key, t.Value, t.Effect)
```
Comment (njtran) [inline pkg/utils/pretty/pretty.go:83]: If there's no value, this is an empty =, can you adjust this so we don't include the = if we don't need to?

File: pkg/scheduling/taints.go [hunk 10]
```diff
@@ -49,7 +51,7 @@ func (ts Taints) Tolerates(pod *corev1.Pod) (errs error) {
 			tolerates = tolerates || t.ToleratesTaint(&taint)
 		}
 		if !tolerates {
-			errs = multierr.Append(errs, fmt.Errorf("did not tolerate %s=%s:%s", taint.Key, taint.Value, taint.Effect))
+			errs = multierr.Append(errs, fmt.Errorf("did not tolerate %s", pretty.Taint(ts[i])))
```
Comment (njtran) [inline pkg/scheduling/taints.go:54]: nit: just use the taint variable that's already defined, or remove that variable and use this array index throughout

File: pkg/controllers/nodeclaim/termination/controller.go [hunk 11]
```diff
@@ -170,7 +171,7 @@ func (c *Controller) annotateTerminationGracePeriodTerminationTime(ctx context.C
 	nodeClaim.ObjectMeta.Annotations = lo.Assign(nodeClaim.ObjectMeta.Annotations, map[string]string{v1.NodeClaimTerminationTimestampAnnotationKey: terminationTime})
 
 	if err := c.kubeClient.Patch(ctx, nodeClaim, client.MergeFrom(stored)); err != nil {
-		return client.IgnoreNotFound(fmt.Errorf("patching nodeclaim, %w", err))
```
Comment (njtran) [inline pkg/controllers/nodeclaim/termination/controller.go:173]: why remove this?

File: pkg/scheduling/taints.go (hunk 10 above)
Comment (jonathan-innis) [reply pkg/scheduling/taints.go]: Oh yeah. Lol

**Review by njtran — COMMENTED** [review]
/lgtm
/approve
