### PR TITLE
ci: fix flaky test for stale instance type drift

### LINKED ISSUE #1986: Drift Test is Flaking
### Description

**Observed Behavior**:

`Drift [It] should detect stale instance type drift if the instance type offerings aren't compatible with the nodeclaim` test is flaking here and there throughout on different test runs.

See https://github.com/kubernetes-sigs/karpenter/actions/runs/13260477160/attempts/1?pr=852. There are other examples if you look through different [presubmit runs](https://github.com/kubernetes-sigs/karpenter/actions/workflows/presubmit.yaml)

**Expected Behavior**:

Test shouldn't flake

**Reproduction Steps** (Please include YAML):

Run `make deflake` with FOCUS on `should detect stale instance type drift if the instance type offerings aren't compatible with the nodeclaim` and you should eventually be able to repro the flake

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by flavono123**
Fixes #1986 

**Description**

1. change Offering.Requirements of InstanceType over Requirements for setup test; ofs.HasCompatible compare Offering.Requirements with the argument(NodeClaim.Labels in this case) -> so i don't know how the test was passed sometimes
2. fix the key for changing value to Offering.Requirements concerns since a return of lo.Keys is not sorted, the previous key was random.
  a. just one changing is enough so commented another  

chore: remove trailing whitespaces in Makefile

**How was this change tested?**

check the test case is passed on make deflake FOCUS="should detect stale instance type drift if the instance type offerings aren't compatible with the nodeclaim"

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/nodeclaim/disruption/drift_test.go [hunk 1]
```diff
@@ -112,8 +112,12 @@ var _ = Describe("Drift", func() {
 	It("should detect stale instance type drift if the instance type offerings aren't compatible with the nodeclaim", func() {
 		cp.InstanceTypes = lo.Map(cp.InstanceTypes, func(it *cloudprovider.InstanceType, _ int) *cloudprovider.InstanceType {
 			if it.Name == nodeClaim.Labels[corev1.LabelInstanceTypeStable] {
-				newLabels := lo.Keys(nodeClaim.Labels)
-				it.Requirements = scheduling.NewLabelRequirements(map[string]string{newLabels[0]: test.RandomName()})
+				for i := range it.Offerings {
```
Comment (jonathan-innis) [inline pkg/controllers/nodeclaim/disruption/drift_test.go:115]: Oh! This actually isn't good at all -- looks like the default state that we set the generic cloudprovider to is `"drifted"` after a `Reset()` which means that regardless of whether the test _should_ actually pass for the drifted condition that it's checking, it's still going to return drifted at all times in the cloudprovider reason -- probably best to check the reason for "Drifted" in this test as well (in the status condition) so that we avoid cases like this

Comment (jonathan-innis) [reply pkg/controllers/nodeclaim/disruption/drift_test.go:115]: We should absolutely update that cloudprovider.Reset() function though to not return "drifted" by default

Comment (flavono123) [reply pkg/controllers/nodeclaim/disruption/drift_test.go:115]: it sounds like a former work required. feel free to amend or just let me know after that done.

i will take another one from open issues.

File: pkg/controllers/nodeclaim/disruption/drift_test.go [hunk 2]
```diff
@@ -112,8 +112,12 @@ var _ = Describe("Drift", func() {
...
+					it.Offerings[i].Requirements = scheduling.NewLabelRequirements(map[string]string{
+						corev1.LabelTopologyZone: test.RandomName(),
+						// v1.CapacityTypeLabelKey:  test.RandomName(),
```
Comment (jonathan-innis) [inline pkg/controllers/nodeclaim/disruption/drift_test.go:118]: Do you need this comment here if you aren't using this portion?

File: pkg/controllers/nodeclaim/disruption/drift_test.go (hunk 1 above)
Comment (jonathan-innis) [reply pkg/controllers/nodeclaim/disruption/drift_test.go:115]: Just pushed the change -- one comment, then I think this looks like it's good to go

File: pkg/controllers/nodeclaim/disruption/drift_test.go (hunk 2 above)
Comment (flavono123) [reply pkg/controllers/nodeclaim/disruption/drift_test.go]: removed -- the incompatible offering might be split into a topology zone and a capacity for each, but still enough for now

**Review by jonathan-innis — APPROVED** [review]
/lgtm
/approve
