### PR TITLE
fix: address nodeclaims being repeatedly created when host ports for a pending pod would conflict with daemons

### LINKED ISSUE #2083: Karpenter scale out infinitely when a pod use host port already used
### Description

**Observed Behavior**:
- Karpenter trigger scale up infinitely

Image

Image

**Expected Behavior**:

- do not trigger scale up, just show event like Cluster Autoscaler

Image

**Reproduction Steps** (Please include YAML):
1. deploy daemonset which uses hostport `x`
2. deploy deployment which uses hostport `x`
3. the pod cannot schedule because of no free port, but karpenter trigger scale up continously

1. daemonset
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-test
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: daemon-test
  template:
    metadata:
      labels:
        name: daemon-test
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: daemon-test
        image: nginx
        ports:
        - name: web
          containerPort: 80
          hostPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

```

2. deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          hostPort: 8080
```

**Versions**:
- Chart Version:  20.24.0
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.31.6-eks-bc803b4
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### LINKED ISSUE #2093: confusion about nodeClaim finalizer
### Description

**Observed Behavior**:

https://github.com/kubernetes-sigs/karpenter/blob/76aaae988ca94e8a5eb8d479663ce120fe4b07b9/pkg/controllers/nodeclaim/lifecycle/controller.go#L184-L188

> *Only delete Nodes if the NodeClaim has not been registered.*

As the comments say, we should delete the node when NodeClaim is not registered, but it seems that the code logic is not like that, right?

**Expected Behavior**:

```git
-       if nodeClaim.StatusConditions().Get(v1.ConditionTypeRegistered).IsTrue() {
+       if nodeClaim.StatusConditions().Get(v1.ConditionTypeRegistered).IsFalse() {
```

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: master
- Kubernetes Version (`kubectl version`):

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by rschalo**
Fixes #2083
Fixes #2093 

**Description**
When attempting to schedule a pending pod to existing capacity, host ports for all pods on that node are checked and influence scheduling decisions. When needing to make a new NodeClaim, there are no pods from which to get this information.

This change looks at daemon set pods that are compatible with the NodeClaimTemplate being used for the pending pods and then checks if required host ports will be available.

**How was this change tested?**
Unit test addition that shows pending pod does not schedule. Additionally, this log fires when run in my dev cluster:
>`
{"level":"ERROR","time":"2025-03-25T23:45:29.227Z","logger":"controller","caller":"provisioning/provisioner.go:357","message":"could not schedule pod","commit":"76aaae9-dirty","controller":"provisioner","namespace":"","name":"","reconcileID":"0b9f3a42-15f2-4323-9e99-d01a32fd4e32","Pod":{"name":"nginx-deployment-5c4df47f4d-cfmmz","namespace":"default"},"error":"incompatible with nodepool \"arm-2cpu\", daemonset overhead={\"cpu\":\"250m\",\"memory\":\"200Mi\",\"pods\":\"6\"}, checking host port usage, IP=0.0.0.0 Port=8080 Proto=TCP conflicts with existing HostPort configuration IP=0.0.0.0 Port=8080 Proto=TCP"}
`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/provisioning/scheduling/scheduler.go [hunk 1]
```diff
@@ -469,6 +471,22 @@ func getDaemonOverhead(nodeClaimTemplates []*NodeClaimTemplate, daemonSetPods []
...
+// getDaemonHostPortUsage tracks requested host ports for daemonsets, given a nodeclaimtemplate
+func getDaemonHostPortUsage(nodeClaimTemplates []*NodeClaimTemplate, daemonSetPods []*corev1.Pod) map[*NodeClaimTemplate]*scheduling.HostPortUsage {
+	nctToOccupiedPorts := map[*NodeClaimTemplate]*scheduling.HostPortUsage{}
+	for _, nct := range nodeClaimTemplates {
+		hostPortUsage := scheduling.NewHostPortUsage()
+		// gather compatible daemon sets for the NodeClaimTemplate of a NodePool
+		for _, pod := range lo.Filter(daemonSetPods, func(p *corev1.Pod, _ int) bool { return isDaemonPodCompatible(nct, p) }) {
+			hostPortUsage.Add(pod, scheduling.GetHostPorts(pod))
+		}
+		if _, ok := nctToOccupiedPorts[nct]; !ok {
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/scheduling/scheduler.go:483]: What do we need to do an `ok` check for?

File: pkg/controllers/provisioning/suite_test.go [hunk 2]
```diff
@@ -826,6 +826,24 @@ var _ = Describe("Provisioning", func() {
 			Expect(*allocatable.Cpu()).To(Equal(resource.MustParse("4")))
 			Expect(*allocatable.Memory()).To(Equal(resource.MustParse("4Gi")))
 		})
+		FIt("should account for daemonset hostports", func() {
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/suite_test.go:829]:
```suggestion
		It("should account for daemonset hostports", func() {
```

File: pkg/controllers/provisioning/scheduling/scheduler.go (hunk 1 above)
Comment (rschalo) [reply pkg/controllers/provisioning/scheduling/scheduler.go:483]: Originally had to debug a nil ptr issue and then forgot to take this out.

**Review by jonathan-innis — APPROVED** [review]
/lgtm
/approve
