### PR TITLE
fix: no longer allow the same hostname to take multiple capacity

### LINKED ISSUE #2318: Reservation manager panics and increased pod scheduling latency on large deployment scale up after v1.5.0
### Description

**Observed Behavior**:
We see increased scale up latency with pods frequently being stuck in Pending for over 10 minutes starting with the upgrade from v1.4.0 to v1.5.0:
```
{"level":"ERROR","time":"2025-06-17T22:06:16.876Z","logger":"controller","message":"Observed a panic","controller":"disruption","namespace":"","name":"","reconcileID":"c34c94ca-8cac-4913-87be-8fd86357e1c6","panic":"attempted to over-reserve an offering with reservation id \"cr-09ac5c8da40022bfa\"","stacktrace":"goroutine 494 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x4773930, 0xc07b6a65a0}, {0x3a59c40, 0xc075ca9880})\n\tk8s.io/apimachinery@v0.32.3/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:108 +0x112\npanic({0x3a59c40?, 0xc075ca9880?})\n\truntime/panic.go:792 +0x132\nsigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*ReservationManager).Reserve(0xc0484ed810, {0xc08e458740, 0x1b}, {0xc0873eafb8, 0x1, 0xc06ab36ba0?})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/provisioning/scheduling/reservationmanager.go:76 +0x285\nsigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*NodeClaim).Add(0xc07a87f088, 0xc024dd5208, 0xc04a197398?, 0xc06ab36ba0, {0xc0873eafa8?, 0x1?, 0x1?}, {0xc0873eafb8, 0x1, 0x1})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/provisioning/scheduling/nodeclaim.go:171 +0x353\nsigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).addToInflightNode(0xc0065801c0, {0x4773930, 0xc08666b140}, 0xc024dd5208)\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/provisioning/scheduling/scheduler.go:528 +0x25f\nsigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).add(0xc0065801c0, {0x4773930, 0xc08666b140}, 0xc024dd5208)\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/provisioning/scheduling/scheduler.go:453 +0x8d\nsigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).trySchedule(0xc0065801c0, {0x4773930, 0xc08666b140}, 0xc024dd5208)\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/provisioning/scheduling/scheduler.go:401 +0x90\nsigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).Solve(0xc0065801c0, {0x4773930, 0xc08666b140}, {0xc0abc38dc8, 0x39, 0x57})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/provisioning/scheduling/scheduler.go:368 +0x8ef\nsigs.k8s.io/karpenter/pkg/controllers/disruption.SimulateScheduling({0x47739d8, 0xc01bc7ad90}, {0x4788480, 0xc0007da870}, 0xc0002638c8, 0xc000a7ac00, {0xc01bd6a008, 0xb, 0xc09ab3ef60?})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/disruption/helpers.go:115 +0x151d\nsigs.k8s.io/karpenter/pkg/controllers/disruption.(*consolidation).computeConsolidation(0xc0007aa980, {0x47739d8, 0xc01bc7ad90}, {0xc01bd6a008, 0xb, 0x1fb})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/disruption/consolidation.go:137 +0xe5\nsigs.k8s.io/karpenter/pkg/controllers/disruption.(*MultiNodeConsolidation).firstNConsolidationOption(0xc0007aa980, {0x4773930, 0xc07b6a6600}, {0xc01bd6a008, 0x15, 0x1fb}, 0x15)\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/disruption/multinodeconsolidation.go:136 +0x2e5\nsigs.k8s.io/karpenter/pkg/controllers/disruption.(*MultiNodeConsolidation).ComputeCommand(0xc0007aa980, {0x4773930, 0xc07b6a6600}, 0xc05a603e00, {0xc0577d8608, 0x1fb, 0x318})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/disruption/multinodeconsolidation.go:88 +0x3eb\nsigs.k8s.io/karpenter/pkg/controllers/disruption.(*Controller).disrupt(0xc0007aaa80, {0x4773930, 0xc07b6a6600}, {0x47769c0, 0xc0007aa980})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/disruption/controller.go:184 +0x5dd\nsigs.k8s.io/karpenter/pkg/controllers/disruption.(*Controller).Reconcile(0xc0007aaa80, {0x4773930, 0xc07b6a65a0})\n\tsigs.k8s.io/karpenter@v1.4.1-0.20250523044835-349487633193/pkg/controllers/disruption/controller.go:146 +0x885\nsigs.k8s.io/karpenter/pkg/controllers/disruption.(*Controller).Register.AsReconciler.func1({0x4773930?, 0xc07b6a65a0?}, {{{0x0?, 0x0?}, {0x416fa5b?, 0x5?}}})\n\tgithub.com/awslabs/operatorpkg@v0.0.0-20250425180727-b22281cd8057/singleton/controller.go:26 +0x2f\nsigs.k8s.io/controller-runtime/pkg/reconcile.TypedFunc[...].Reconcile(...)\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/reconcile/reconcile.go:124\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0a7bc3f20?, {0x4773930?, 0xc07b6a65a0?}, {{{0x0?, 0x0?}, {0x0?, 0x0?}}})\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x479f340, {0x4773968, 0xc0000495e0}, {{{0x0, 0x0}, {0x0, 0x0}}}, 0x0)\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334 +0x3ad\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x479f340, {0x4773968, 0xc0000495e0})\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294 +0x21b\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 303\n\tsigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:251 +0x6e8\n"}
```

**Expected Behavior**:
No regression in pod scheduling latency.

**Reproduction Steps** (Please include YAML):
We see this in a production environment with a large deployment of a new replicaset with 500+ pods using partially fulfilled reserved instances (~20% of capacity). Reverting to v1.4.0 fixes the issue.

**Versions**:
- Chart Version: v1.5.0
- Kubernetes Version (`kubectl version`): v1.29.15

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by DerekFrank**
Fixes #2318

**Description**

Add a short circuit to the `Reserve` function that will prevent the same hostname from taking multiple capacity

**How was this change tested?**

Added a new test package for the reservation manager and a test specifically for the functionality.

## Prior to code change:

```
Running Suite: Scheduling - /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling
==============================================================================================================================
Random Seed: 1751928679

Will run 27 of 318 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS••••••••••••••••••••••••••
------------------------------
• [PANICKED] [0.006 seconds]
ReservationManager Integration Scenarios [It] should handle the same hostname reserving multiple times
/Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager_test.go:509

  [PANICKED] Test Panicked
  In [It] at: /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager.go:80 @ 07/07/25 15:51:22.021

  attempted to over-reserve an offering with reservation id "medium-reserved"

  Full Stack Trace
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*ReservationManager).Reserve(0x140007266f0, {0x1065512c5, 0x6}, {0x14000766f40, 0x1, 0x14000a48c40?})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager.go:80 +0x23c
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling_test.init.func1.6.6()
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager_test.go:512 +0xbc
------------------------------

Summarizing 1 Failure:
  [PANICKED!] ReservationManager Integration Scenarios [It] should handle the same hostname reserving multiple times
  /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager.go:80

Ran 27 of 318 Specs in 3.830 seconds
FAIL! -- 26 Passed | 1 Failed | 0 Pending | 291 Skipped
--- FAIL: TestScheduling (3.83s)
FAIL
FAIL    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling   4.767s
```

```
/opt/homebrew/bin/go test -timeout 30s -run ^TestScheduling$ sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling
Running Suite: Scheduling - /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling
==============================================================================================================================
Random Seed: 1752093653

Will run 1 of 316 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
• [PANICKED] [2.148 seconds]
Scheduling Reserved Instance Types [It] should handle multiple pods on reserved nodes
/Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/suite_test.go:4301

  [PANICKED] Test Panicked
  In [It] at: /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager.go:82 @ 07/09/25 13:40:58.104

  attempted to over-reserve an offering with reservation id "r-small-instance-type"

  Full Stack Trace
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*ReservationManager).Reserve(0x140000de970, {0x14000a0c660, 0x19}, {0x140001a2778, 0x1, 0x14000b08660?})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager.go:82 +0x248
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*NodeClaim).Add(0x1400031f8c8, 0x14000051b08, 0x14000694900?, 0x14000b08660, {0x140001a2760?, 0x1?, 0x1?}, {0x140001a2778, 0x1, 0x1})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/nodeclaim.go:171 +0x288
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).addToInflightNode(0x140006360e0, {0x104bedeb0, 0x14000320460}, 0x14000051b08)
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/scheduler.go:517 +0x1fc
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).add(0x140006360e0, {0x104bedeb0, 0x14000320460}, 0x14000051b08)
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/scheduler.go:442 +0x80
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).trySchedule(0x140006360e0, {0x104bedeb0, 0x14000320460}, 0x14000051b08)
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/scheduler.go:390 +0x64
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling.(*Scheduler).Solve(0x140006360e0, {0x104bedeb0, 0x14000320460}, {0x14000b12140, 0x14, 0x14})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/scheduler.go:357 +0x75c
    sigs.k8s.io/karpenter/pkg/controllers/provisioning.(*Provisioner).Schedule(0x140006a5c80, {0x104bede08, 0x140008d7530})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/provisioner.go:343 +0xa10
    sigs.k8s.io/karpenter/pkg/test/expectations.ExpectProvisionedNoBinding({0x104bede08, 0x140008d7530}, {0x104c00400, 0x1400014f320}, 0x140007b58c8, {0x104bfa7e0, 0x14000515c20}, 0x140006a5c80, {0x14000498000, 0x14, ...})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/test/expectations/expectations.go:324 +0xc8
    sigs.k8s.io/karpenter/pkg/test/expectations.ExpectProvisioned({0x104bede08, 0x140008d7530}, {0x104c00400, 0x1400014f320}, 0x140007b58c8, {0x104bfa7e0, 0x14000515c20}, 0x140006a5c80, {0x14000498000, 0x14, ...})
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/test/expectations/expectations.go:304 +0x94
    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling_test.init.func7.12.8()
        /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/suite_test.go:4327 +0x3d8
------------------------------

Summarizing 1 Failure:
  [PANICKED!] Scheduling Reserved Instance Types [It] should handle multiple pods on reserved nodes
  /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling/reservationmanager.go:82

Ran 1 of 316 Specs in 5.495 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 315 Skipped
--- FAIL: TestScheduling (5.50s)
    logger.go:146: 2025-07-09T13:40:58.100-0700 DEBUG   provisioning/provisioner.go:316 computing scheduling decision for provisionable pod(s)  {"pending-pods": 20, "deleting-pods": 0}
FAIL
FAIL    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling   6.396s
FAIL
```

## After Code Change:

```
Running Suite: Scheduling - /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling
==============================================================================================================================
Random Seed: 1751928734

Will run 27 of 318 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•••••••••••••••••••••••••••SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Ran 27 of 318 Specs in 4.515 seconds
SUCCESS! -- 27 Passed | 0 Failed | 0 Pending | 291 Skipped
PASS | FOCUSED
FAIL    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling   5.411s
FAIL
```

```
 /opt/homebrew/bin/go test -timeout 30s -run ^TestScheduling$ sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling
Running Suite: Scheduling - /Users/derekff/code/karpenter/forks/karpenter-testing-fork/pkg/controllers/provisioning/scheduling
==============================================================================================================================
Random Seed: 1752093967

Will run 1 of 316 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•

Ran 1 of 316 Specs in 6.470 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 315 Skipped
PASS | FOCUSED
FAIL    sigs.k8s.io/karpenter/pkg/controllers/provisioning/scheduling   7.375s
FAIL
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/provisioning/scheduling/reservationmanager.go [hunk 1]
```diff
@@ -71,11 +71,15 @@ func (rm *ReservationManager) CanReserve(hostname string, offering *cloudprovide
 
 func (rm *ReservationManager) Reserve(hostname string, offerings ...*cloudprovider.Offering) {
 	for _, of := range offerings {
+		reservations, ok := rm.reservations[hostname]
+		if ok && reservations.Has(of.ReservationID()) {
```
Comment (engedaam) [inline pkg/controllers/provisioning/scheduling/reservationmanager.go:77]: Why are adding this check? Even if we have a reservation don't we still want to update the number of instance we are able to launch?

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 2]
```diff
@@ -0,0 +1,517 @@
...
+								Requirements: pscheduling.NewLabelRequirements(map[string]string{
+									v1.CapacityTypeLabelKey: v1.CapacityTypeReserved,
+								}),
+							},
+						},
+					}),
+				},
+			}
+			duplicateRM := scheduling.NewReservationManager(duplicateReservationTypes)
+			Expect(duplicateRM).ToNot(BeNil())
```
Comment (engedaam) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: Do we want to assert what we are expecting the reservations generally?

File: pkg/controllers/provisioning/scheduling/reservationmanager.go (hunk 1 above)
Comment (jmdeal) [reply pkg/controllers/provisioning/scheduling/reservationmanager.go:77]: The issue is that this function is meant to be idempotent. For a given NodeClaim, it should only be able to make a single reservation per offering (since it can only ever result in a single instance being launched). This behavior was maintained in the `CanReserve` function, but wasn't added here.

File: pkg/controllers/provisioning/scheduling/reservationmanager.go [hunk 3]
```diff
@@ -71,11 +71,15 @@ func (rm *ReservationManager) CanReserve(hostname string, offering *cloudprovide
 
 func (rm *ReservationManager) Reserve(hostname string, offerings ...*cloudprovider.Offering) {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager.go:74]: IMO it would be good to add a comment to both `CanReserve` and `Reserve` indicating that both are meant to be idempotent.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 4]
```diff
@@ -0,0 +1,517 @@
...
+		// Extract offerings from instance types
+		offerings = nil // Reset offerings slice
+		for _, it := range instanceTypes {
+			offerings = append(offerings, it.Offerings)
+		}
+
+		rm = scheduling.NewReservationManager(map[string][]*cloudprovider.InstanceType{"": instanceTypes})
+	})
+
+	Describe("NewReservationManager", func() {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: I'm wondering how valuable these tests are in their current state. The only assertion we're making is that the resulting ReservationManager is non-nil, but we don't actually make any assertions on it's current state. These tests would still pass if this was the implementation for `NewReservationManager`:
```go
func NewReservationManager(...) *ReservationManager {
    return &ReservationManager{}
}
```
If we want to include construction tests, I think we would want to expose the internal state and verify that it was constructed correctly or just defer this testing to the behavior tests and implicitly test that it's constructed correctly by getting the expected results from `Reserve` and `Release`.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 5]
```diff
@@ -0,0 +1,517 @@
...
+			It("should return true when capacity is available", func() {
+				canReserve := rm.CanReserve("hostname-1", testOffering)
+				Expect(canReserve).To(BeTrue())
+			})
+
+			It("should return true when hostname already has the reservation", func() {
+				// First reserve
+				rm.Reserve("hostname-1", testOffering)
+				// Should still be able to "reserve" the same reservation for the same hostname
+				canReserve := rm.CanReserve("hostname-1", testOffering)
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: It would be better to test this with an offering with a capacity of 1, or we should exhaust the remaining capacity. Right now this would succeed even if we were still double counting the reservation for this hostname.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 6]
```diff
@@ -0,0 +1,517 @@
...
+				Expect(canReserve).To(BeTrue())
+			})
+		})
+
+		Context("With No Capacity", func() {
+			It("should return false when capacity is exhausted", func() {
+				// Exhaust all capacity
+				for i := 0; i < 3; i++ {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: nit: here (and elsewhere) where we want to iterate over all offerings, could we use the capacity of the offering as the upper bound rather than a hard coded value? Just looking to save some work in-case we ever need to update these tests.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go (hunk 5 above)
Comment (jmdeal) [reply pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: Looks like this is actually covered in the "With No Capacity" case - If we want to keep this test I think it would make sense to update the comment to indicate that this test case **does not** verify that we're using the same reservation for the same hostname. I'm not sure it's too valuable to keep, but I could see the argument of keeping it for completeness.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 7]
```diff
@@ -0,0 +1,517 @@
...
+			It("should successfully reserve capacity", func() {
+				rm.Reserve("hostname-1", testOffering1)
+				// Verify reservation was made by checking CanReserve behavior
+				canReserve := rm.CanReserve("hostname-1", testOffering1)
+				Expect(canReserve).To(BeTrue())
+			})
+
+			It("should not double-reserve for the same hostname and reservation", func() {
+				// Reserve twice for the same hostname and reservation
+				rm.Reserve("hostname-1", testOffering1)
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: We should use test offering 2 for this test right? With test offering 1, even if we double reserved for hostname-1 there would still be capacity for hostname-2 left.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 8]
```diff
@@ -0,0 +1,517 @@
...
+				canReserve := rm.CanReserve("hostname-4", testOffering1)
+				Expect(canReserve).To(BeFalse())
+			})
+		})
+
+		Context("Multiple Reservations", func() {
+			It("should handle multiple offerings in a single call", func() {
+				rm.Reserve("hostname-1", testOffering1, testOffering2)
+
+				// Verify both reservations were made
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go:197]: This doesn't actually verify that both reservations are made, right? I could see us surfacing a method on the reservation manage for testing to check if a reservation is made for a given hostname. I could potentially also see us surfacing a function that surfaces the remaining capacity for a given offering.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 9]
```diff
@@ -0,0 +1,517 @@
...
+
+		Context("Valid Releases", func() {
+			It("should release a single reservation", func() {
+				// Reserve and then release
+				rm.Reserve("hostname-1", testOffering1)
+				rm.Release("hostname-1", testOffering1)
+
+				// Verify the reservation is no longer tracked for this hostname
+				// but capacity should be restored
+				canReserve := rm.CanReserve("hostname-2", testOffering1)
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: I also don't see how this actually verifies that the release was successful - testOffering1 has a capacity of 3, even if we didn't release the reservation for hostname-1 we'd be able to make a reservation.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 10]
```diff
@@ -0,0 +1,517 @@
...
+				rm.Reserve("hostname-1", testOffering1)
+				// Should not panic when releasing from a different hostname
+				Expect(func() {
+					rm.Release("hostname-2", testOffering1)
+				}).ToNot(Panic())
+			})
+		})
+
+		Context("Multiple Releases", func() {
+			It("should handle multiple offerings in a single call", func() {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go:276]: I think this is another case where we don't actually verify what we need to - `CanReserve` should succeed even if we didn't successfully release the offerings. This would be a good candidate for a method on ReservationManager for checking if a reservation exists for a given offering. Same story for "should handle partial release".

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go:1]: An overall theme for my review of these tests is that we should expose additional methods on ReservationManager to help directly inspect internal state. The main issue I have is using `CanReserve` as a proxy for checking if a reservation exists for a given offering. IMO these tests could be improved a lot by adding the following functions:
```go
func (rm *ReservationManager) HasReservation(hostname string, offering *cloudprovider.Offering) bool
func (rm *ReservationManager) RemainingCapacity(offering *cloudprovider.Offering) int
```

Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go:1]: Adding unit tests for this is great, and is an obvious gap in the original implementation. The reservation manager was implicitly tested through the scheduling tests, but this is a better way to ensure we exercise all possible states. That being said, this particular bug **could** have been caught through scheduling tests, and I think we should expand those tests so that it would have been. Something like the following test scenario should have caught the bug:
- Create a reserved offering with capacity `n`
- Create `m` pending pods with affinity (to ensure they schedule to the same node). `m` must be greater or equal to `n`
- Attempt to provision. The scheduler should panic since we will have attempted to create `m` reservations for an offering with capacity `n`.

Comment (DerekFrank) [reply pkg/controllers/provisioning/scheduling/reservationmanager_test.go:1]: I was hesitant to add new public functions for the explicit purpose of testing, but it wasn't a strong opinion

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go (hunk 5 above)
Comment (DerekFrank) [reply pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: I'll use a single capacity res and keep it for completeness

File: pkg/controllers/provisioning/scheduling/reservationmanager.go [hunk 11]
```diff
@@ -90,3 +96,17 @@ func (rm *ReservationManager) Release(hostname string, offerings ...*cloudprovid
 		}
 	}
 }
+
+// Used for testing only
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager.go]: nit: I think we can drop this comment from both functions. While it is only used for testing atm, I think it's a reasonable method for `ReservationManager`to surface and there's no reason you couldn't use it outside of testing. That's honestly why I was comfortable suggesting to add these in the first place.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 12]
```diff
@@ -0,0 +1,419 @@
...
+					corev1.ResourceCPU:    resource.MustParse("8"),
+					corev1.ResourceMemory: resource.MustParse("16Gi"),
+					corev1.ResourcePods:   resource.MustParse("40"),
+				},
+				Offerings: []*cloudprovider.Offering{oneCapacityOffering},
+			}),
+		}
+
+		// Extract offerings from instance types
+		offerings = make(map[string]cloudprovider.Offerings) // Reset offerings map
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: nit: we generally don't use make
```suggestion
		offerings = map[string]cloudprovider.Offerings{} // Reset offerings map
```

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 13]
```diff
@@ -0,0 +1,419 @@
...
+				// Should still be able to "reserve" the same reservation for the same hostname
+				canReserve := rm.CanReserve("hostname-1", oneCapacityOffering)
+				Expect(canReserve).To(BeTrue())
+			})
+		})
+
+		Context("With No Capacity", func() {
+			It("should return false when capacity is exhausted", func() {
+				// Exhaust all capacity
+				for i := 0; i < oneCapacityOffering.ReservationCapacity; i++ {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: nit: can simplify this with the newish range syntax. This holds for all of the three clause for loops.
```suggestion
				for i := range oneCapacityOffering.ReservationCapacity {
```

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 14]
```diff
@@ -0,0 +1,419 @@
...
+		})
+	})
+
+	Describe("Reserve", func() {
+		Context("Single Reservations", func() {
+			It("should successfully reserve capacity", func() {
+				rm.Reserve("hostname-1", threeCapacityOffering)
+				// Verify reservation was made by checking CanReserve behavior
+				canReserve := rm.CanReserve("hostname-1", threeCapacityOffering)
+				Expect(canReserve).To(BeTrue())
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: We should use `HasReservation` here, right? We should use this everywhere where we want to verify if we successfully made a reservation.
```suggestion
				Expect(rm.HasReservation("hostname-1", threeCapacityOffering)).To(BeTrue())
```

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 15]
```diff
@@ -0,0 +1,414 @@
...
+
+				// Then reserve both (one existing, one new)
+				rm.Reserve("hostname-1", threeCapacityOffering, twoCapacityOffering)
+
+				// Verify both are reserved and capacity is correctly tracked
+				Expect(rm.HasReservation("hostname-1", threeCapacityOffering)).To(BeTrue())
+				Expect(rm.HasReservation("hostname-1", twoCapacityOffering)).To(BeTrue())
+
+				// Verify capacity was only decremented once for testtwoCapacityOffering
+				canReserveOther1 := rm.CanReserve("hostname-2", threeCapacityOffering)
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: This would pass regardless right? We're reserving the `threeCapacityOffering` twice but even if we double counted that would leave one remaining.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 16]
```diff
@@ -0,0 +1,414 @@
...
+				// Release only one
+				rm.Release("hostname-1", threeCapacityOffering)
+
+				// Verify only the released one has restored capacity
+				Expect(rm.HasReservation("hostname-1", threeCapacityOffering)).To(BeFalse())
+				Expect(rm.HasReservation("hostname-1", twoCapacityOffering)).To(BeTrue())
+			})
+		})
+
+		Context("Capacity Restoration", func() {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go:301]: IMO we should use `RemainingCapacity` here to assert that capacity has returned to the expected level, rather than trying to determine it via `CanReserve`

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 17]
```diff
@@ -0,0 +1,414 @@
...
+
+			// Verify all reservations are tracked
+			Expect(rm.HasReservation("host-1", threeCapacityOffering)).To(BeTrue())
+			Expect(rm.HasReservation("host-1", twoCapacityOffering)).To(BeTrue())
+			Expect(rm.HasReservation("host-2", twoCapacityOffering)).To(BeTrue())
+			Expect(rm.HasReservation("host-2", oneCapacityOffering)).To(BeTrue())
+			Expect(rm.HasReservation("host-3", threeCapacityOffering)).To(BeTrue())
+
+			// Verify capacity limits
+			Expect(rm.CanReserve("host-4", twoCapacityOffering)).To(BeFalse())  // Exhausted (2 capacity, 2 used)
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: IMO it makes more sense to do these checks with `RemainingCapacity`

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 18]
```diff
@@ -0,0 +1,414 @@
...
+			Expect(rm.CanReserve("host-4", threeCapacityOffering)).To(BeTrue()) // Still available (3 capacity, 2 used)
+			Expect(rm.CanReserve("host-4", oneCapacityOffering)).To(BeFalse())  // Exhausted (1 capacity, 1 used)
+		})
+
+		It("should handle reservation conflicts correctly", func() {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: nit: I'm not sure this case provides a more complex scenario than the non-integration test cases. We could probably drop it.

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 19]
```diff
@@ -0,0 +1,414 @@
...
+			Expect(rm.HasReservation("host-1", twoCapacityOffering)).To(BeFalse())  // Released, so not reserved for host-1
+			Expect(rm.HasReservation("host-1", threeCapacityOffering)).To(BeTrue()) // Still reserved for host-1
+			Expect(rm.HasReservation("host-2", threeCapacityOffering)).To(BeTrue()) // Still reserved for host-2
+			Expect(rm.HasReservation("host-2", oneCapacityOffering)).To(BeFalse())  // Released, so not reserved for host-2
+			Expect(rm.HasReservation("host-3", twoCapacityOffering)).To(BeTrue())   // Reserved for host-3
+
+			// Check capacity availability
+			Expect(rm.CanReserve("host-4", twoCapacityOffering)).To(BeTrue())   // Should have 1 available (2 total, 1 used by host-3)
+			Expect(rm.CanReserve("host-4", threeCapacityOffering)).To(BeTrue()) // Should have 1 available (3 total, 2 used)
+			Expect(rm.CanReserve("host-4", oneCapacityOffering)).To(BeTrue())   // Should have 1 available (1 total, 0 used after release)
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: Same comment here - I'd inspect this using `RemainingCapacity`

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 20]
```diff
@@ -0,0 +1,414 @@
...
+			Expect(rm.HasReservation("host-1", oneCapacityOffering)).To(BeFalse())
+			Expect(rm.HasReservation("host-1", twoCapacityOffering)).To(BeFalse())
+			Expect(rm.HasReservation("host-1", threeCapacityOffering)).To(BeFalse())
+			// Verify we can use full capacity again
+			rm.Reserve("host-2", twoCapacityOffering)
+			rm.Reserve("host-3", twoCapacityOffering)
+			Expect(rm.CanReserve("host-4", twoCapacityOffering)).To(BeFalse()) // Should be exhausted again
+		})
+
+		It("should handle the same hostname reserving multiple times", func() {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: Does this offer any additional value over the base scenarios?

File: pkg/controllers/provisioning/scheduling/suite_test.go [hunk 21]
```diff
@@ -4298,6 +4298,42 @@ var _ = Context("Scheduling", func() {
 			Expect(node.Labels).To(HaveKeyWithValue(corev1.LabelInstanceTypeStable, targetInstanceTypeName))
 			Expect(node.Labels).To(HaveKeyWithValue(v1.NodePoolLabelKey, nodePool.Name))
 		})
+		It("should handle multiple pods on reserved nodes", func() {
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/suite_test.go:4301]: For this to have caught this issue, two things must be true:
- The pods must schedule to the same node
- There must be more pods than there are available instances for the capacity reservation

Here, only the latter holds. They need to schedule to the same node so that we overcount for a given hostname.

Comment (DerekFrank) [reply pkg/controllers/provisioning/scheduling/suite_test.go:4301]: This did capture the issue, I put the evidence in the description. You can see on 4331 that we verify they all scheduled to the same node. I can put a pod affinity on the pods if you think that would be better

Comment (jmdeal) [reply pkg/controllers/provisioning/scheduling/suite_test.go:4301]: Discussed offline that we'll add the affinity term to guarantee that they always schedule to the same node. Relying on pod requests vs instance size has bit us in the past when these global sizes are changed for other tests. An affinity will ensure that this test would fail if we needed to provision multiple nodes.

File: pkg/controllers/provisioning/scheduling/reservationmanager.go [hunk 22]
```diff
@@ -90,3 +96,15 @@ func (rm *ReservationManager) Release(hostname string, offerings ...*cloudprovid
 		}
 	}
 }
+
+func (rm *ReservationManager) HasReservation(hostname string, offering *cloudprovider.Offering) bool {
+	reservation, exists := rm.reservations[hostname]
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/scheduling/reservationmanager.go]:
```suggestion
	reservation, ok := rm.reservations[hostname]
```

nit: typical go style uses `ok`

File: pkg/controllers/provisioning/scheduling/reservationmanager.go [hunk 23]
```diff
@@ -90,3 +96,15 @@ func (rm *ReservationManager) Release(hostname string, offerings ...*cloudprovid
 		}
 	}
 }
+
+func (rm *ReservationManager) HasReservation(hostname string, offering *cloudprovider.Offering) bool {
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/scheduling/reservationmanager.go:100]: nit: Can you use this function in the `Reserve()` call since this has the same logic? I get you may have to re-check the map, so I could go either way on it

File: pkg/controllers/provisioning/scheduling/reservationmanager.go [hunk 24]
```diff
@@ -90,3 +96,15 @@ func (rm *ReservationManager) Release(hostname string, offerings ...*cloudprovid
...
+	reservation, exists := rm.reservations[hostname]
+	if exists && reservation.Has(offering.ReservationID()) {
+		return true
+	}
+	return false
+}
+
+func (rm *ReservationManager) RemainingCapacity(offering *cloudprovider.Offering) int {
```
Comment (jonathan-innis) [inline pkg/controllers/provisioning/scheduling/reservationmanager.go:108]: Why do you need this? Just for readability? If so, we should probably be using this elsewhere when we are checking capacity

Comment (DerekFrank) [reply pkg/controllers/provisioning/scheduling/reservationmanager.go:108]: We needed it for more accurate unit testing. we could use it elsewhere. I wanted to keep the scope of the fix down

File: pkg/controllers/provisioning/scheduling/reservationmanager.go (hunk 23 above)
Comment (DerekFrank) [reply pkg/controllers/provisioning/scheduling/reservationmanager.go:100]: The function is meant for testing right now

File: pkg/controllers/provisioning/scheduling/reservationmanager_test.go [hunk 25]
```diff
@@ -0,0 +1,371 @@
...
+			})
+
+			It("should correctly track capacity after multiple reserve/release cycles", func() {
+				// Reserve, release, reserve again
+				rm.Reserve("hostname-1", threeCapacityOffering)
+				rm.Release("hostname-1", threeCapacityOffering)
+				rm.Reserve("hostname-2", threeCapacityOffering)
+
+				// Should still have capacity available
+				Expect(rm.RemainingCapacity(threeCapacityOffering)).ToNot(Equal(0))
```
Comment (jmdeal) [inline pkg/controllers/provisioning/scheduling/reservationmanager_test.go]: nit: even if release didn't work, there would be 1 remaining. Better to assert the expected remaining capacity.
```suggestion
				Expect(rm.RemainingCapacity(threeCapacityOffering)).To(Equal(2))
```

**Review by jmdeal — COMMENTED** [review]
One last comment
