### PR TITLE
fix: address disruption taint race condition

### LINKED ISSUE #1167: Pod gets evicted still even with "karpenter.sh/do-not-disrupt" annotation
### Description

**Observed Behavior**:
Pod with "karpenter.sh/do-not-disrupt" annotation still get evicted - not sure how to reproduce this cause this seems to be intermittent

Some examples of Karpenter evicting pods despite claiming the same pods to be undisruptable just moments ago.

```
Apr 3, 2024 @ 16:10:41.000: Cannot disrupt Node: Pod "mesh-west/runner-zjioycxf-project-14388-concurrent-0lvg45" has "karpenter.sh/do-not-disrupt" annotation
Apr 3, 2024 @ 16:10:41.000: Cannot disrupt NodeClaim: Pod "mesh-west/runner-zjioycxf-project-14388-concurrent-0lvg45" has "karpenter.sh/do-not-disrupt" annotation
...
(Events from Datadog) Apr 3, 4:10:41 pm: Events from the Pod mesh-west/runner-zjioycxf-project-14388-concurrent-0lvg45 - Evicted pod - Events emitted by the karpenter
```

```
Apr 2, 2024 @ 13:09:04.000: Cannot disrupt Node: Pod "mesh-west/runner-su7-c7kj-project-14388-concurrent-0qc8j7" has "karpenter.sh/do-not-disrupt" annotation
Apr 2, 2024 @ 13:09:04.000: Cannot disrupt NodeClaim: Pod "mesh-west/runner-su7-c7kj-project-14388-concurrent-0qc8j7" has "karpenter.sh/do-not-disrupt" annotation
...
(Events from Datadog) Apr 2, 1:09:05 pm: Events from the Pod mesh-west/runner-su7-c7kj-project-14388-concurrent-0qc8j7 - Evicted pod - Events emitted by the karpenter
```

**Expected Behavior**:
Pod with "karpenter.sh/do-not-disrupt" annotation shouldn't be evicted

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 0.35.2
- Kubernetes Version (`kubectl version`): EKS v1.23.17-eks-508b6b3

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jmdeal**
Fixes #1167 

**Description**
Implements a short-term, zero-API mitigation for the consolidation race condition called out in issues #651 and #1167. This PR will not close out issue #651 since we still may change the exact mechanism as part of the holistic taint redesign for #624. 

**How was this change tested?**
Manual validation + karpenter-provider-aws E2E suite

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/disruption/controller.go [hunk 1]
```diff
@@ -58,8 +58,11 @@ type Controller struct {
 	lastRun       map[string]time.Time
 }
 
-// pollingPeriod that we inspect cluster to look for opportunities to disrupt
-const pollingPeriod = 10 * time.Second
+const (
+	// pollingPeriod that we inspect cluster to look for opportunities to disrupt
+	pollingPeriod         = 10 * time.Second
+	commandExecutionDelay = 10 * time.Second
```
[the remark this answers is not in the document]
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go:64]: I made it longer when testing and missed changing it back, this should be 5 seconds. This is based on cluster autoscaler's default for their equivalent field, `node-delete-delay-after-taint`. This was sufficient in my testing (with 5s) and I haven't been able to find any instances of users needing to change this delay.

File: pkg/controllers/disruption/controller.go [hunk 2]
```diff
@@ -191,11 +196,45 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+			state.RequireNoScheduleTaint(ctx, c.kubeClient, false, stateNodes...),
+		)
+	}
+
+	// After adding the NoSchedule taint to the proposed candidates, revalidate the candidates after a waiting period. This addresses a race condition
+	// where pods with the `karpenter.sh/do-not-disrupt` annotation can be scheduled after the command has been validated but before the nodes have been tainted.
+	// A waiting period is used to ensure Karpenter's internal cluster state has synced and all pods are accounted for.
+	select {
+	case <-ctx.Done():
+		return multierr.Append(fmt.Errorf("interrupted (command-id: %s)", commandID), state.RequireNoScheduleTaint(ctx, c.kubeClient, false, stateNodes...))
```
[the remark this answers is not in the document]
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go:210]: Good point, I threw an error here based on what we were already do for consolidation: https://github.com/kubernetes-sigs/karpenter/blob/43da3604c14097ab1ee3ca360af5a82446a4db4d/pkg/controllers/disruption/emptynodeconsolidation.go#L86-L90
but you're right that there's no value in attempting to untaint. I could go either way with surfacing this as an error at all, but chose to follow what we were already doing.

File: pkg/controllers/disruption/controller.go [hunk 3]
```diff
@@ -191,11 +196,45 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+	case <-c.clock.After(commandExecutionDelay):
+	}
+
+	currentCandidates, err := GetCandidates(ctx, c.cluster, c.kubeClient, c.recorder, c.clock, c.cloudProvider, candidateFilter, c.queue)
```
[the remark this answers is not in the document]
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go]: I think I've arrived at a better approach. I've realized the validation behavior ideally should be slightly different for each disruption method so it seems reasonable to extend the method interface. This leaves only the common logic in the disruption controller (untainting / canceling the command). Will probably split this and tainting into a separate function from executeCommand, more for readability than anything else.

File: pkg/controllers/disruption/controller.go [hunk 4]
```diff
@@ -194,10 +203,42 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
 		return multierr.Append(fmt.Errorf("tainting nodes (command-id: %s), %w", commandID, err), state.RequireNoScheduleTaint(ctx, c.kubeClient, false, stateNodes...))
 	}
 
+	select {
+	case <-ctx.Done():
+		return fmt.Errorf("interrupted (command-id: %s)", commandID)
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:208]:
```suggestion
		return fmt.Errorf("interrupted command (command-id: %s)", commandID)
```

File: pkg/controllers/disruption/controller.go [hunk 5]
```diff
@@ -58,8 +58,13 @@ type Controller struct {
...
 }
 
-// pollingPeriod that we inspect cluster to look for opportunities to disrupt
-const pollingPeriod = 10 * time.Second
+const (
+	// pollingPeriod that we inspect cluster to look for opportunities to disrupt
+	pollingPeriod = 10 * time.Second
+
+	// commandExecutionDelay is the duration spent waiting after tainting candidate nodes before validaing the command
+	commandValidationDelay = 5 * time.Second
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:66]: Is this a dart throw? Or are there metrics you're using to drive this decision

File: pkg/controllers/disruption/controller.go [hunk 6]
```diff
@@ -194,10 +203,42 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+	if err != nil {
+		return fmt.Errorf("validating command, determining candidates, %w", err)
+	}
+	disruptionBudgetMapping, err := BuildDisruptionBudgets(ctx, c.cluster, c.clock, c.kubeClient, c.recorder)
+	if err != nil {
+		return fmt.Errorf("validating command, building disruption budgets, %w", err)
+	}
+	validatedCommand := m.ValidateCommand(ctx, cmd, disruptionBudgetMapping, candidates...)
+	if len(validatedCommand.candidates) == 0 {
+		logging.FromContext(ctx).Infof("abandoning disruption attempt, 0 out of %d nodes are still valid candidates", len(cmd.candidates))
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:224]: You could alternatively phrase it like this
```suggestion
		logging.FromContext(ctx).Infof("abandoning disruption attempt, %d candidates are no longer valid", len(cmd.candidates))
```

File: pkg/controllers/disruption/controller.go [hunk 7]
```diff
@@ -194,10 +203,42 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+	// This addresses a race conditions where pods can schedule to the candidate nodes after the command has been finalized, but before the candidates were tainted.
+	candidates, err := GetCandidates(ctx, c.cluster, c.kubeClient, c.recorder, c.clock, c.cloudProvider, m.ShouldDisrupt, c.queue)
+	if err != nil {
+		return fmt.Errorf("validating command, determining candidates, %w", err)
+	}
+	disruptionBudgetMapping, err := BuildDisruptionBudgets(ctx, c.cluster, c.clock, c.kubeClient, c.recorder)
+	if err != nil {
+		return fmt.Errorf("validating command, building disruption budgets, %w", err)
+	}
+	validatedCommand := m.ValidateCommand(ctx, cmd, disruptionBudgetMapping, candidates...)
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:222]: From looking at the various `ValidateCommand()` calls, it looks like they all implement the following 

1. Map L214 candidates to command.Candidates
2. do `method.ShouldDisrupt`
3. check disruption budgets

I personally don't think we need another interface method for this, as the method specific behavior is already encapsulated in the GetCandidates() call on L214. I could see doing a helper function for the disruption budget mapping check. WDYT?

File: pkg/controllers/disruption/controller.go [hunk 8]
```diff
@@ -194,10 +203,42 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+		invalidatedCandidates := lo.FilterMap(cmd.candidates, func(candidate *Candidate, _ int) (*state.StateNode, bool) {
+			return candidate.StateNode, !lo.ContainsBy(validatedCommand.candidates, func(c *Candidate) bool {
+				return c.Name() == candidate.Name()
+			})
+		})
+		if err = state.RequireNoScheduleTaint(ctx, c.kubeClient, false, invalidatedCandidates...); err != nil {
+			return fmt.Errorf("untainting invalidated candidates, %w", err)
+		}
+		logging.FromContext(ctx).Infof("updated disruption command after validation, disrupting via %s %s", m.Type(), validatedCommand)
+	}
```
Comment (njtran) [inline pkg/controllers/disruption/controller.go:237]: Should we be continuing if a subset of the candidates are no longer candidates? Let's say we had 100 candidates, and now only 1 candidate is invalid. We need to either re-do a scheduling simulation to know what the replacement should be, or just abandon the command entirely. 

For reference, we abandon the command for consolidation.

File: pkg/controllers/disruption/controller.go [hunk 9]
```diff
@@ -194,10 +203,42 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+	case <-ctx.Done():
+		return fmt.Errorf("interrupted (command-id: %s)", commandID)
+	case <-c.clock.After(commandValidationDelay):
+	}
+
+	// Revalidate the proposed command after the node has been tainted.
+	// This addresses a race conditions where pods can schedule to the candidate nodes after the command has been finalized, but before the candidates were tainted.
+	candidates, err := GetCandidates(ctx, c.cluster, c.kubeClient, c.recorder, c.clock, c.cloudProvider, m.ShouldDisrupt, c.queue)
+	if err != nil {
+		return fmt.Errorf("validating command, determining candidates, %w", err)
```
Comment (tzneal) [inline pkg/controllers/disruption/controller.go:216]: This leaves nodes tainted, right?

File: pkg/controllers/disruption/controller.go [hunk 10]
```diff
@@ -194,10 +203,42 @@ func (c *Controller) executeCommand(ctx context.Context, m Method, cmd Command,
...
+	}
+	disruptionBudgetMapping, err := BuildDisruptionBudgets(ctx, c.cluster, c.clock, c.kubeClient, c.recorder)
+	if err != nil {
+		return fmt.Errorf("validating command, building disruption budgets, %w", err)
```
Comment (tzneal) [inline pkg/controllers/disruption/controller.go:220]: Same comment

File: pkg/controllers/disruption/consolidation_test.go [hunk 11]
```diff
@@ -3750,7 +3750,7 @@ var _ = Describe("Consolidation", func() {
 			Expect(ExpectNodes(ctx, env.Client)).To(HaveLen(1))
 			ExpectExists(ctx, env.Client, nodes[0])
 		})
-		It("should not consolidate if the action becomes invalid during the node TTL wait", func() {
+		FIt("should not consolidate if the action becomes invalid during the node TTL wait", func() {
```
Comment (njtran) [inline pkg/controllers/disruption/consolidation_test.go:3753]:
```suggestion
		It("should not consolidate if the action becomes invalid during the node TTL wait", func() {
```

File: pkg/controllers/disruption/emptynodeconsolidation.go [hunk 12]
```diff
@@ -96,6 +96,10 @@ func (c *EmptyNodeConsolidation) ComputeCommand(ctx context.Context, disruptionB
 	// Get the current representation of the proposed candidates from before the validation timeout
 	// We do this so that we can re-validate that the candidates that were computed before we made the decision are the same
 	candidatesToDelete := mapCandidates(cmd.candidates, validationCandidates)
+	if invalidatedCount := len(cmd.candidates) - len(candidatesToDelete); invalidatedCount != 0 {
```
Comment (njtran) [inline pkg/controllers/disruption/emptynodeconsolidation.go:99]: Isn't this the same as len(candidates) != len(candidatesToDelete)

File: pkg/controllers/disruption/emptynodeconsolidation.go [hunk 13]
```diff
@@ -96,6 +96,10 @@ func (c *EmptyNodeConsolidation) ComputeCommand(ctx context.Context, disruptionB
...
+		logging.FromContext(ctx).Debugf("abandoning empty node consolidation attempt, %d candidates are no longer valid, command is no longer valid, %s", invalidatedCount, cmd)
```
Comment (njtran) [inline pkg/controllers/disruption/emptynodeconsolidation.go:100]: Can we add these formatted directives into structured values in the logger?
```suggestion
		logging.FromContext(ctx).Debugf("abandoning empty node consolidation attempt, %d candidates are no longer valid, command is no longer valid, %s", invalidatedCount, cmd)
```

File: pkg/controllers/disruption/validation.go [hunk 14]
```diff
@@ -80,37 +79,54 @@ func (v *Validation) IsValid(ctx context.Context, cmd Command) (bool, error) {
 		case <-v.clock.After(waitDuration):
 		}
 	}
-	// Get the current representation of the proposed candidates from before the validation timeout
-	// We do this so that we can re-validate that the candidates that were computed before we made the decision are the same
-	// We perform filtering here to ensure that none of the proposed candidates have blocking PDBs or do-not-evict/do-not-disrupt pods scheduled to them
-	validationCandidates, err := GetCandidates(ctx, v.cluster, v.kubeClient, v.recorder, v.clock, v.cloudProvider, v.ShouldDisrupt, v.queue)
+	validatedCandidates, err := v.validateCandidates(ctx, cmd.candidates...)
+	if len(validatedCandidates) == 0 || err != nil {
```
Comment (njtran) [inline pkg/controllers/disruption/validation.go:83]: Why would we want to continue if the number of candidates isn't 0, but isn't the set of candidates we started off with?

Comment (jmdeal) [reply pkg/controllers/disruption/validation.go:81]: `ValidateCandidates` returns an empty slice if the full set of candidates were not valid. If the candidates were all valid, the returned slice is the updated Candidate representations.

File: pkg/controllers/disruption/controller.go (hunk 5 above)
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go]: Resolving, updated approach does not involve taint and wait strategy. This number was a slight dart through that was justified by the default value for the same value in CAS.

File: pkg/controllers/disruption/controller.go (hunk 7 above)
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go]: Resolving, current approach removes the interface function. Realistically we only see this race occur for consolidation where the race window is expanded due to the validating scheduling simulation so I've added a second validation pass after that check and am going to opt to leave it at that for now.

File: pkg/controllers/disruption/controller.go (hunk 8 above)
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go]: Like you called out the decision we make here is going to differ depending on the disruption type. It was handled in the ValidateCommand function for that reason. If we want to cancel the entire command it should return a command with no candidates. Otherwise it should return a command with a reduced number of candidates and we would untaint the invalidated candidates here.

File: pkg/controllers/disruption/emptynodeconsolidation.go (hunk 12 above)
Comment (jmdeal) [reply pkg/controllers/disruption/emptynodeconsolidation.go]: Resolving since this was removed, but yes. I changed it temporarily to move that math out of the log statement but was going to change it back if I kept this log line.

File: pkg/controllers/disruption/controller.go (hunk 9 above)
Comment (jmdeal) [reply pkg/controllers/disruption/controller.go]: Yes, that was a miss. I've swapped out this PR with an alternate implementation that doesn't involve tainting during validation but I'll fix this in my backup branch in case we need to go back.

File: pkg/controllers/disruption/validation.go (hunk 14 above)
Comment (jonathan-innis) [reply pkg/controllers/disruption/validation.go:81]: I think @njtran's point is that a failed validation should be an error here. Reading this function, I would assume I either get: 1) No error and the mapped candidates or 2) No mapped candidates and an error. The in-between state is a little confusing. I wonder if a special "FailedValidation" error could handle this better. At a high-level, I wonder if we could replace `isValid` with a `FailedValidation` error generally.

File: pkg/utils/pod/scheduling.go [hunk 15]
```diff
@@ -53,10 +53,12 @@ func IsReschedulable(pod *v1.Pod) bool {
 // - Is an active pod (isn't terminal or actively terminating)
 // - Doesn't tolerate the "karpenter.sh/disruption=disrupting" taint
 // - Isn't a mirror pod (https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/)
+// - Doesn't have the "karpenter.sh/do-not-disrupt=true" annotation
 func IsEvictable(pod *v1.Pod) bool {
 	return IsActive(pod) &&
 		!ToleratesDisruptionNoScheduleTaint(pod) &&
-		!IsOwnedByNode(pod)
+		!IsOwnedByNode(pod) &&
+		IsDisruptable(pod)
```
Comment (jonathan-innis) [inline pkg/utils/pod/scheduling.go:61]: We're going to stop evicting `karpenter.sh/do-not-disrupt` pods in this change? That's a major breaking change and not something that I think we can do without the grace period mechanism that we've been talking about. We've told users that they can expect that there is a way to bail out of pods hanging nodes during drain by doing a `kubectl delete node`. I agree that we need to reverse this, but shouldn't do so without giving these same users a mechanism to gracefully delete their nodes with `kubectl delete node`

Comment (jonathan-innis) [reply pkg/utils/pod/scheduling.go:61]: This also strikes me as out of scope of this race condition fix -- something we want to do long-term, but probably not in the context of this bug fix

File: pkg/controllers/disruption/validation.go (hunk 14 above)
Comment (jonathan-innis) [reply pkg/controllers/disruption/validation.go:81]: The other thing that I don't love but was trying to figure out a good solve for and couldn't think of anything: a `Validate` function returns back retrieved data. Realistically, you want to retrieve the data, map the data, then validate the data. I get this is a little difficult since we've coupled some of our validation in the GetCandidates() logic. More of a musing and to see if you can think of something better that has closer semantic meaning than just `ValidateCandidates`.

Comment (jmdeal) [reply pkg/controllers/disruption/validation.go:81]: We could definitely replace this with a `ValidationError`, basically just needed a mechanism to differentiate between a 'fatal' error that would be propogated back up the call stack and an error reported vs a non-fatal error where we just discard the consolidation attempt.

File: pkg/utils/pod/scheduling.go (hunk 15 above)
Comment (jmdeal) [reply pkg/utils/pod/scheduling.go:61]: Sounds good, I included it here as a mechanism to ensure that these pods aren't disrupted even if they slip through but I agree it can be decoupled.

**Review by jonathan-innis — APPROVED** [review]
/lgtm
/approve

File: pkg/controllers/disruption/validation.go [hunk 16]
```diff
@@ -35,82 +35,114 @@ import (
...
+	}
+	return nil
+}
+
+// ValidateCandidates gets the current representation of the provided candidates and ensures that they are all still valid.
+// For a candidate to still be valid, the following conditions must be met:
+//
+//	a. It must pass the global candidate filtering logic (no blocking PDBs, no do-not-disrupt annotation, etc)
+//	b. It must not have any pods nominated for it
+//	c. It must still be disruptible without violating node disruption budgets
```
Comment (njtran) [inline pkg/controllers/disruption/validation.go:116]: spelling nit
```suggestion
//	c. It must still be disruptable without violating node disruption budgets
```

**Review by njtran — COMMENTED** [review]
/lgtm
/approve
